# Generated by Django 3.1 on 2020-08-25 11:35

import ckeditor.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckeditor', ckeditor.fields.RichTextField(verbose_name='CKEditor')),
                ('tinymce', tinymce.models.HTMLField(verbose_name='TinyMCE')),
            ],
            options={
                'verbose_name': 'rich text model',
                'verbose_name_plural': 'rich text models',
            },
        ),
    ]
