# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-08-13 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='name_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='name_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='name_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
