# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-08-13 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shop', '0004_auto_20200813_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfeature',
            name='name',
        ),
    ]
