# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-08-13 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shop', '0005_remove_itemfeature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='name_uk',
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sw_shop.AttributeValue'),
            preserve_default=False,
        ),
    ]
