# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-08-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shop', '0006_auto_20200813_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemattribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itemattribute',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='itemattribute',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='itemattribute',
            name='name_uk',
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sw_shop.Attribute'),
            preserve_default=False,
        ),
    ]
