# Generated by Django 3.1 on 2020-08-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shop', '0007_auto_20200813_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
