# Generated by Django 3.1 on 2020-08-13 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_shop', '0008_auto_20200813_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sw_shop.itemcategory'),
            preserve_default=False,
        ),
    ]
